name: CI-Pipeline for Production

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kustomize-guestbook
          push: true
          # KORREKTUR: toLower()-Funktion verwenden
          tags: ghcr.io/${{ toLower(github.repository_owner) }}/argocd-example-apps:${{ github.sha }}

      - name: Erneuter Checkout für den Push
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Kubernetes Manifest aktualisieren
        run: |
          cd kustomize-guestbook
          # KORREKTUR: toLower()-Funktion verwenden
          kustomize edit set image guestbook=ghcr.io/${{ toLower(github.repository_owner) }}/argocd-example-apps:${{ github.sha }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push
