name: CI-Pipeline for Production

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Nur Schreibrechte für den Code nötig

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      # Login bei Docker Hub mit den erstellten Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kustomize-guestbook
          push: true
          # Image-Format für Docker Hub: BENUTZERNAME/IMAGE-NAME:TAG
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/argocd-example-apps:${{ github.sha }}

      - name: Erneuter Checkout für den Push
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Kubernetes Manifest aktualisieren
        run: |
          cd kustomize-guestbook
          # Kustomize auf den Docker Hub Pfad anpassen
          kustomize edit set image guestbook=${{ secrets.DOCKERHUB_USERNAME }}/argocd-example-apps:${{ github.sha }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push
